# Generated by Django 3.2.9 on 2021-11-09 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab02app', '0003_auto_20211109_2344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='image',
        ),
    ]
