# Generated by Django 3.2.9 on 2021-11-09 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab02app', '0004_remove_movie_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='file_url',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
